version: "3.3"
services:
  traefik:
    image: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.network=traefik-net"
      - "--entrypoints.web.address=:80"
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`traefik.oninhome.io`)"
        - "traefik.http.routes.api.service=api@internal" #Aqui no se que posa de que es per a que el dashboard pugui accedir a la api
  
  etherpad:
    image: etherpad/etherpad:1.8.11
    networks:
      - traefik-net
      - backend
    
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.etherpad.rule=Host(`etherpad.traefik.oninhome.io`)"
        - "traefik.http.routers.etherpad.entrypoints=web"
        - "traefik.http.services.etherpad.loadbalancer.server.port=9001"


  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: admin


  adminer:
    image: adminer
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`adminer.traefik.oninhome.io`)"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  traefik-net:
    external: true
  backend:
    external: true
